webtalk_init -webtalk_dir C:/Users/shenc/OneDrive - nyu.edu/6463_AHD/LAB4/rc5_enc/rc5_enc.sim/sim_1/behav/xsim/xsim.dir/rc5_enc_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Fri Oct 12 23:40:05 2018" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2018.2.1 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2288692" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "b5bb4c12-9898-4d6d-8b1f-1499cb4dfd32" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "37b10079850e4670b1d1e74a0b8c9f8b" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "26" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i5-6300U CPU @ 2.40GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2496 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "4.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "1 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.06_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "5488_KB" -context "xsim\\usage"
webtalk_transmit -clientid 2874652469 -regid "" -xml C:/Users/shenc/OneDrive - nyu.edu/6463_AHD/LAB4/rc5_enc/rc5_enc.sim/sim_1/behav/xsim/xsim.dir/rc5_enc_behav/webtalk/usage_statistics_ext_xsim.xml -html C:/Users/shenc/OneDrive - nyu.edu/6463_AHD/LAB4/rc5_enc/rc5_enc.sim/sim_1/behav/xsim/xsim.dir/rc5_enc_behav/webtalk/usage_statistics_ext_xsim.html -wdm C:/Users/shenc/OneDrive - nyu.edu/6463_AHD/LAB4/rc5_enc/rc5_enc.sim/sim_1/behav/xsim/xsim.dir/rc5_enc_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
